version: "3.8"
services:
  db:
    container_name: mysql_database
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./mysqldata:/var/lib/mysqldata/data
    restart: always
    environment:
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - db_network 
  api:
    image: aimelive/demo-credit-api
    build: ./
    container_name: api_backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - db_network
networks:
  db_network:
    driver: bridge      
